// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa9XiJe5wGaDvKmvo8XoQYE_LXxky_M7E',
    appId: '1:752876696495:web:4fd6bb0c014b9686d7755a',
    messagingSenderId: '752876696495',
    projectId: 'cricscor-c1438',
    authDomain: 'cricscor-c1438.firebaseapp.com',
    storageBucket: 'cricscor-c1438.firebasestorage.app',
    measurementId: 'G-4L9975WTQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ZkwjxSh5U1_k29bh1THoDGyLC1enlps',
    appId: '1:752876696495:android:0312f437161e8c35d7755a',
    messagingSenderId: '752876696495',
    projectId: 'cricscor-c1438',
    storageBucket: 'cricscor-c1438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInpFncQ9XpzmVekVsuDNN4IZns8s9YU4',
    appId: '1:752876696495:ios:cdf323cbf29da23fd7755a',
    messagingSenderId: '752876696495',
    projectId: 'cricscor-c1438',
    storageBucket: 'cricscor-c1438.firebasestorage.app',
    iosClientId: '752876696495-5cioeseupe3klfgbssetot17lri1tqmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cricscor',
  );
}
